#                    ____                 _
#                   |  _ \ _ __ _   _ ___| | __
#                   | | | | '__| | | / __| |/ /
#                   | |_| | |  | |_| \__ \   <
#                   |____/|_|   \__,_|___/_|\_\
#              By ItsMCB and other Drusk contributors

#     A message from Martin (ItsMCB), the lead developer:
#     I truly hope this plugin fits your needs. If you come across a problem or have a suggestion, please open an issue on GitHub.
#     Additionally, if you need help or more information, please check out the "README" on GitHub.
#     GitHub: https://github.com/ItsMCB/Drusk

# The following lines with hashtags are comments designed to help you understand the options in this configuration file

file-version: 1

tab:
  enabled: true
  top:
    - '                                        '
    - "&d&lLibre Galaxy"
    - "&7play.libregalaxy.org"
    - ''
  bottom:
    - ''
    - "&7Server: &d%server_name% &8| &7Ping: &d%player_ping%ms"
    - "&7Online: &d%server_online% &8| &7Global: &d%bungee_total%"
    - ''
spawn:
  location: null

events:
  join:
    enabled: true
    # Leave empty to disable default message
    message: "&e%player_name% jumped into the server"
    title:
      title-message: "&aLibre Galaxy"
      subtitle-message: "&eWelcome"
      fade-in: 1
      stay: 5
      fade-out: 1
    spawn-teleport:
      on-first-join: true
      on-join: true
  leave:
    enabled: true
    # Leave empty to disable default message
    message: "&e%player_name% left the server to take a break"
  death:
    enabled: true
    # Leave empty to disable default message
    message: "&e%player_name% got rekt"