name: Drusk
version: '${version}'
main: me.itsmcb.drusk.Drusk
api-version: 1.21.3
authors: [ ItsMCB ]
description: Small but desirable features that are configurable and aimed at benefiting a variety of server setups
website: https://github.com/ItsMCB/Drusk
depend:
  - VexelCore
softdepend:
  - Citizens
  - CoreProtect
libraries:
  - com.fasterxml.jackson.core:jackson-core:2.18.2
  - com.fasterxml.jackson.core:jackson-databind:2.18.2
  - com.fasterxml.jackson.core:jackson-annotations:2.18.2
  - net.dv8tion:JDA:5.2.2