name: Drusk
version: '${version}'
main: me.itsmcb.drusk.Drusk
api-version: 1.18
authors: [ ItsMCB ]
description: Small but desirable features that are configurable and aimed at benefiting a variety of server setups
website: https://github.com/ItsMCB/Drusk
depend:
  - VexelCore
softdepend:
  - Citizens
  - CoreProtect
libraries:
  - com.fasterxml.jackson.core:jackson-core:2.13.0
  - com.fasterxml.jackson.core:jackson-databind:2.13.0
  - com.fasterxml.jackson.core:jackson-annotations:2.13.0